services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social_media_dev
    ports:
      - '3000:3000' # Common port for web development
      - '5000:5000' # Alternative port if needed
    volumes:
      - .:/app # Mount current directory to /app in container
    networks:
      - dev-network
    # Keep container running
    tty: true
    stdin_open: true

networks:
  dev-network:
    driver: bridge
